### ISSUE TITLE
Remove language referencing other modules

### ISSUE THREAD

**Issue by jessepisel** [learn-co-curriculum/dsc-distributions-intro-v2-2#1]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [x] Other (explain below)

### Source

```

```

### Concern

The current language references other modules. 

## (Optional) Proposed Solution

This language needs to be removed

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by Cheffrey2000** [comment]
Fixed with the following commit [be53184](https://github.com/learn-co-curriculum/dsc-distributions-intro-v2-2/commit/be53184f70862c0e3791b407d2192a74f0cb35a3)
