### ISSUE TITLE
Wording mentions content that hasn't been presented yet

### ISSUE THREAD

**Issue by joeldmott** [learn-co-curriculum/dsc-distributions-intro-v2-2#2]
## Link to Canvas

https://learning.flatironschool.com/courses/6535/pages/statistical-distributions-introduction?module_item_id=562036

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [x] Other (explain below)

### Source

```

```

### Concern

I think there's just a minor issue with the wording at the start of this introductory lesson after the curriculum was updated recently. The very first paragraph states "This is the second of two sections covering foundational statistical concepts. Now that you have covered the essential set theory and probability theory...", but that hasn't happened yet. 

Not a bgi deal, but it did have me doing a double-take and wondering whether I'd missed something. 

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by jessepisel** [comment]
fixed with https://github.com/learn-co-curriculum/dsc-distributions-intro-v2-2/commit/e31f51f5a6735cbe97cccaabded9c4f3c311746b
